### ISSUE TITLE
Describing rolls

### ISSUE THREAD

**Issue by dardanbujupaj** [dice-roller/rpg-dice-roller#222]
**Is your feature request related to a problem? Please describe.**
I'm using `DiceRoller` to display a list of recently rolled notations and their results, the results can also be clicked to roll the same notation again. This works fine, but it's a bit hard to figure out what the rolls where meant for, especially if there were a lot of rolls. 

**Describe the solution you'd like**
I would love to have the option to give every `DiceRoll` a separate description, so that for any given roll in the `DiceRoller`-log I can look up what they were rolled for.
Two solutions come to mind to solve this:

Solution 1: Describing the roll in the notation
[FoundryVTT](https://foundryvtt.com/article/dice/#describing) has two options for that in its `/roll` (in-chat roll) command.
a. Roll description: `/roll 1d20 # Roll for initiative` -> has *roll for initiative* as description for the whole roll
b. Dice description: `/roll 1d20[Initiative]+1d4[Bonus]` -> has *Initiative* as description for the 1d20 and *Bonus* as description for the 1d4

These work pretty well. However, this would mean that the the dice grammar needs to be changed and I'm not sure how much work that would mean.

Solution 2:
Another option would be to add an additional (optional) parameter to the `roll`-method.
Something like:
`DiceRoll.roll(notation: string, description?: string)` respectively `DiceRoller.roll(notation: string, description?: string)`

And add the property 'description: string' to the `DiceRoll`-class.

I like solution 2 more. But it would mean that the api would change (not a breaking change as it's only an optional parameter).

**Describe alternatives you've considered**
Alternatively, I could track the descriptions in a separate Map or something, but as the user can change the text representation of the DiceRoll using any of its properties, this would get complicated very fast.

Also I think this feature (especially Solution 2) would be an elegant addition to `rpg-dice-roller`.

**Comment by dardanbujupaj** [comment]
Just realized that the module is not written in Typescript, so the code I proposed is not valid. Please understand it as pseudocode ;)

**Comment by dardanbujupaj** [comment]
On second thought, it might be a bit more far-sighted to make the second parameter an object and call it `options` with one of the properties being `description`, so that potential other properties in the future might go there as well.

**Comment by GreenImp** [comment]
Thanks for the suggestion.
It's not something that I've ever thought of supporting, because I always saw things like that as outside scope for the library - ie. you could roll the two dice separately, and add the text when you output as a string. I've also tried to stay away from things that are more part of the "chat" feature of Systems like Roll20.

However I'm thinking that there might actually be some benefit to this after all, and it's worth a look.

You've got some good suggestions on how it could work.

## Solution 1

As you've noted, [FoundryVTT](https://foundryvtt.com/article/dice/#describing) have two options here:

1. Roll description: `/roll 1d20 # Roll for initiative` -> has roll for initiative as description for the whole roll
2. Dice description: `/roll 1d20[Initiative]+1d4[Bonus]` -> has Initiative as description for the 1d20 and Bonus as description for the 1d4

For what it's worth, it looks like Roll20 provide similar: https://help.roll20.net/hc/en-us/articles/360037773133-Dice-Reference#DiceReference-InlineLabels

### Option 1 - `#`

This seems to be more of a higher level description, for use in the game chat.
However, I suppose it could work, but it would mean that no other notation could be added after the description:
```javascript
1d20 # Roll for initiative + 2d10
```
The ` + 2d10` would be classed as part of the description.

You could also go the JS style route (or even both):
```javascript
1d20 // Roll for initiative 
```

### Option 2 `[...]`

This could work. I don't _think_ the notation would conflict with anything, as I'm fairly sure we're not using square brackets for anything else.

Roll20 have an example that adds a description to more than just a dice role:
```javascript
2d20+5[Fire Damage] + 3d6+5[Ice Damage]
```

So the "Fire Damage" label assumedly get assigned to the `2d20+5` equation, rather than just the `5`. Here's what  the output looks like:
![Screenshot from 2021-04-21 22-00-04](https://user-images.githubusercontent.com/1846676/115620451-1a78b800-a2ed-11eb-9459-939acb01e6f3.png)

It could be hard to achieve a description on more than a single die roll, due to how the results are stored.


## Solution 2

I don't think option 2 would allow the flexibility that you're after. If you rolled a notation like `4d6+2d10`, you'd have no way of adding a description to both rolls:
```javascript
diceRoll.roll('4d6+2d10', {description: 'initiative'});
```
We'd be adding the description to the entire notation.

I suppose, an alternative would be to have it as an indexed array:
```javascript
diceRoll.roll('4d6+2d10', {descriptions: ['initiative', 'bonus']});
```

Another downside of this method is that it doesn't allow a typical user, who can only write notations, to add a description.


## Output

A pertinent question is, how would you expect the roll output to look? Neither Rol20 or FoundryVTT show the description in the roll results - choosing to show them separately instead.

So, are you just wanting the description stored against the objects, so you can grab them and display them yourself, or would you want them to show up in the output, something like;

Rolling:
```
2d20[Fire Damage] + 3d6[Ice Damage]
```

Would output:
```javascript
2d20[Fire Damage] + 3d6[Ice Damage]: [11, 11]+[6, 6, 4] = 38 
```

Or even:
```javascript
2d20[Fire Damage] + 3d6[Ice Damage]: [11, 11][Fire Damage]+[6, 6, 4][Ice Damage] = 38 
```

**Comment by dardanbujupaj** [comment]
I totally understand your concerns and I would accept it as well if you said it's out of scope for the library.

To clarify my use case: 
I use obsidian.md to keep notes and I made a plugin to quickly roll inside the app (which uses the dice roller). In a separate panel I show a history of all dice rolls like this:
<img width="309" alt="dice_history" src="https://user-images.githubusercontent.com/16074028/115697715-18057500-a364-11eb-9065-d8eec37d8364.png">

This uses The `DiceRoll.notation` and `DiceRoll.total` properties. (when hovering a roll it also shows the `output`)


My goal would be to add the ability to add a description to rolls wich would be shown like this:
<img width="309" alt="dice_history_description" src="https://user-images.githubusercontent.com/16074028/115698154-99f59e00-a364-11eb-949c-d5934532183b.png">

So Solution 1: Option 1 and Solution 2 would suffice for me after all.

I see the same problem as you regarding describing multiple rolls (as in Solution1:Option2): 
> It could be hard to achieve a description on more than a single die roll, due to how the results are stored.

Even if we provide an indexed array of descriptions on the resulting `DiceRoll` we do not know how to split the dice roll properly.
Parsing the Roll20 example using the `Parser` I get the following. 
````
Parser.parse('1d20+5+3d6+1')
[
  StandardDice {
    [Symbol(qty)]: 1,
    [Symbol(sides)]: 20,
    [Symbol(min-value)]: 1,
    [Symbol(max-value)]: 20,
    [Symbol(modifiers)]: Map(0) {}
  },
  '+',
  5,
  '+',
  StandardDice {
    [Symbol(qty)]: 3,
    [Symbol(sides)]: 6,
    [Symbol(min-value)]: 1,
    [Symbol(max-value)]: 6,
    [Symbol(modifiers)]: Map(0) {}
  },
  '+',
  1
]
````

Assuming an array `DiceRoll.descriptions` of `['Fire Damage', 'Ice Damage']` in this case I would assign FireDamage to 1d20 and Ice Damage to +5.

Altough using RollGroups would work fine I guess -> `{1d20+5}[Fire Damage] + {3d6+3}[Ice Damage]`
````
roller.Parser.parse('{1d20+5}+{3d6+1}')
[
  RollGroup {
    [Symbol(expressions)]: [ [Array] ],
    [Symbol(modifiers)]: Map(0) {}
  },
  '+',
  RollGroup {
    [Symbol(expressions)]: [ [Array] ],
    [Symbol(modifiers)]: Map(0) {}
  }
]
````


My initial suggestion of using Solution 2 was based on the assumption that it's the least amount of work of the three (which still holds I think). But I understand your concerns that users, who can only write notations, should also be able to add descriptions. So I agree, that any of the options (or both) of Solution 1 would fit the library better.


As for the output. To be honest, I didn't even think about that yet. But showing them in the output would be a nice addition.

If the description is for the whole DiceRoll I think I would expect something like this:
````
Roll for Initiative: 1d20+5: [6]+5 = 11
````
If it's for each dice, your suggestions look good to me. I think I would prefer the first one, to avoid redundant information.

**Comment by GreenImp** [comment]
> Altough using RollGroups would work fine I guess -> `{1d20+5}[Fire Damage] + {3d6+3}[Ice Damage]`

Ah! brilliant idea! That would indeed allow comments to be grouped, because we can then add the comment to the `RollGroup` and `ResultGroup` objects.
I like that idea. Inline comments can then be attached to a single item, or a group.

```javascript
// fire damage is just 5d6
5d6[Fire damage] + 5 + 2d10[Ice damage]

// fire damage is 5d6+5
{5d6 + 5}[Fire damage] + 2d10[Ice damage]
```

With that, I think that both inline comments (`[...]`), and line comments (`# ...`) can work.

I do think I prefer these ideas, over passing a list to the roller, as it does mean that anyone can add comments.

**Comment by dardanbujupaj** [comment]
Yeah I think this is going in the right direction.

Correct me if I'm wrong but there's no possibility to add a comment to a single number as those are stored as `number`. e.g.
````
3d6[Fire] + 3[Ice]
````
I think this is acceptible though. For reference: FoundryVTT throws an error when trying this and Roll20 just ignores it.

**Comment by GreenImp** [comment]
> Correct me if I'm wrong but there's no possibility to add a comment to a single number as those are stored as `number`.

Ah yes, you are correct. Unless we change raw numbers to be stored as some sort of object, then we won't be able to add descriptions to them.

This would be a breaking change though, so perhaps something to add to the backlog.

I think, with the suggested functionality, you could probably get around this by wrapping the number in a roll group though:

```javascript
3d6[Fire] + {3}[Ice]
```

**Comment by dardanbujupaj** [comment]
> I think, with the suggested functionality, you could probably get around this by wrapping the number in a roll group though:

Nice, didn't cross my mind!

I think I have a picture of the whole thing now. Will give it a go at the weekend if that's ok for you? But I have to read up on pegjs first 😅.

**Comment by GreenImp** [comment]
Yeah, that would be great. PRs are always welcome! It's always worth checking out the [contributing guide](https://greenimp.github.io/rpg-dice-roller/contributing/#contributing-code).

It would be really good to see this!

**Comment by GreenImp** [comment]
For reference, below is a list of valid descriptions / comments:

# Multi-line

## Dice

```
3d6[Fire]
3d6[ Fire ]
3d6[ Fi
re ] 

3d6/*Fire*/
3d6/* Fire */
3d6/* Fi
re */
```

## Roll groups

```
{5d6 + 5}[Fire]

{5d6 + 5}/*Fire*/
```


# Single-line

## Dice

```
3d6 //fire
3d6 // fire

3d6 # fire
3d6 #fire
```

## Roll groups

```
{5d6 + 5} //fire
{5d6 + 5} // fire

{5d6 + 5} #fire
{5d6 + 5} # fire
```

**Comment by GreenImp** [comment]
I've been making some headway with this, where the description notation will be cast to a new `Description` object, with a `text` and `type` properties. The type is either "inline" or "multiline".

For example;

```javascript
3d6 // fire
```

Would be:

```javascript
{
  text: 'fire',
  type: 'inline',
}
```

And:

```javascript
3d6[Some description]
```

Would be:

```javascript
{
  text: 'Some description',
  type: 'multiline',
}
```

**Comment by GreenImp** [comment]
This has just gone out in v5.2.0! I'll be adding info about it to the docs when I can.
