### ISSUE TITLE
[Bug]: Notation invalid when the expression has a description

### ISSUE THREAD

**Issue by lucaspiresfernandes** [dice-roller/rpg-dice-roller#287]
### Description

The notation is invalid when the expression ends with a description, preceded by a literal number:

`1d4+2 // For the bug`, but `1d4+2` works.

```
Invalid notation; Expected "(", "-", "abs", "ceil", "cos", "d", "d%", "dF", "exp", "floor", "log", "max", "min", "pow", "round", "sign", "sin", "sqrt", "tan", "{", [0-9], [1-9], or whitespace but "/" found.
```

### Dice Roller version

5.4.1

### Bundle type

ESM

### Node version

18

**Comment by GreenImp** [comment]
This is actually expected.

When you do something like this:

```javascript
1d4+2 // a description
```

You're actually trying to add a description to the literal number `2`. This is because the `+` operator splits it into two different parts.

Only [Dice](https://dice-roller.github.io/documentation/guide/notation/dice.html) or [Roll Groups] (https://dice-roller.github.io/documentation/guide/notation/group-rolls.html) can have a description applied to them, not literal numbers.

If you need to add a description to a group of rolls, numbers etc, you can wrap them in a Roll Group to tell the roller that they are all together:

```javascript
{1d4+2} // a description
```

There are examples of this in the documentation, although I realised it's not overly clear that what you're trying wouldn't work (I'll need to update the docs):
https://dice-roller.github.io/documentation/guide/notation/roll-descriptions.html

**Comment by lucaspiresfernandes** [comment]
Thank you for clarifying this.
